// User Authenticate and Profile Management

export const ITEMS_HAVE_ERROR = "ITEMS_HAVE_ERROR";
export const ITEMS_HAVE_LOADING = "ITEMS_HAVE_LOADING";
export const ITEMS_HAVE_SUCCESS = "ITEMS_HAVE_SUCCESS";
export const WALLET_CONNECT_SUCCESS = "WALLET_CONNECT_SUCCESS";
export const WALLET_DISCONNECT_SUCCESS = "WALLET_DISCONNECT_SUCCESS";
